//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinoView
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public System.DateTime Data { get; set; }
        public decimal KinoPoisk { get; set; }
        public string Description { get; set; }
        public string Actor { get; set; }
        public string Age { get; set; }
        public string Country { get; set; }
        public string Director { get; set; }
        public string Genre { get; set; }
        public decimal Favorite { get; set; }
        public string Image { get; set; }
    }
}
